### ISSUE TITLE
Icon did not get uploaded

### ISSUE THREAD

**Issue by JosefPihrt** [MicrosoftDocs/visualstudio-docs.cs-cz#4]
I used "publish" command to publish my extension (https://marketplace.visualstudio.com/items?itemName=josefpihrt.Roslynator2017). Everything worked fine except one thing: the icon did not get uploaded and it is missing. When I tried to upload vsix (same that had been just published) through browser the icon was uploaded. My manifest.json looks like this:

```json
{
  "$schema": "http://json.schemastore.org/vsix-publish",
  "categories": [ "coding", "other" ],
  "identity": {
    "internalName": "Roslynator2017"
  },
  "overview": "Overview.md",
  "priceCategory": "free",
  "publisher": "josefpihrt",
  "private": false,
  "qna": true,
  "repo": "https://github.com/JosefPihrt/Roslynator"
}
```

Is it necessary to include icon in manifest.json? It shouldn't be according to this site.

Thanks for help.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 71dd9bd6-f1f7-e030-3ee7-3a3faf7d7e59
* Version Independent ID: f4e9045e-daa2-55ed-9449-d13c80e29138
* Content: [Průvodce: Publikování rozšíření sady Visual Studio pomocí příkazového řádku - Visual Studio](https://docs.microsoft.com/cs-cz/visualstudio/extensibility/walkthrough-publishing-a-visual-studio-extension-via-command-line?view=vs-2017)
* Content Source: [docs/extensibility/walkthrough-publishing-a-visual-studio-extension-via-command-line.md](https://github.com/MicrosoftDocs/visualstudio-docs.cs-cz/blob/live/docs/extensibility/walkthrough-publishing-a-visual-studio-extension-via-command-line.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by CeciAc** [comment]
Hello, @JosefPihrt

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
